theme: jekyll-theme-slate
title: Title
url: https://porismjamesdavidson.github.io/

markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links